# Define Bible verses for multiple months
bible_verses = {
    "July": {
        1: "'For I know the plans I have for you,' declares the LORD, 'plans to prosper you and not to harm you, plans to give you hope and a future.' - Jeremiah 29:11",
        2: "'The LORD is my shepherd; I shall not want.' - Psalm 23:1",
        3: "'And we know that in all things God works for the good of those who love him.' - Romans 8:28",
        4: "'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.' - Galatians 5:22",
        5: "'The LORD is my light and my salvation—whom shall I fear?' - Psalm 27:1",
        6: "'I can do all this through him who gives me strength.' - Philippians 4:13",
        7: "'The name of the LORD is a fortified tower; the righteous run to it and are safe.' - Proverbs 18:10",
        8: "'He gives strength to the weary and increases the power of the weak.' - Isaiah 40:29",
        9: "'Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.' - Joshua 1:9",
        10: "'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.' - Nahum 1:7",
        11: "'I sought the LORD, and he answered me; he delivered me from all my fears.' - Psalm 34:4",
        12: "'In all your ways submit to him, and he will make your paths straight.' - Proverbs 3:6",
        13: "'The LORD will fight for you; you need only to be still.' - Exodus 14:14",
        14: "'The LORD is compassionate and gracious, slow to anger, abounding in love.' - Psalm 103:8",
        15: "'Let all that you do be done in love.' - 1 Corinthians 16:14",
        16: "'You are the light of the world. A town built on a hill cannot be hidden.' - Matthew 5:14",
        17: "'If you have faith as small as a mustard seed, you can say to this mountain, Move from here to there, and it will move.' - Matthew 17:20",
        18: "'Cast all your anxiety on him because he cares for you.' - 1 Peter 5:7",
        19: "'The LORD is my strength and my shield; my heart trusts in him, and he helps me.' - Psalm 28:7",
        20: "'And we know that in all things God works for the good of those who love him.' - Romans 8:28",
        21: "'The LORD is my shepherd, I lack nothing.' - Psalm 23:1",
        22: "'Be still, and know that I am God.' - Psalm 46:10",
        23: "'The LORD is righteous in all his ways and faithful in all he does.' - Psalm 145:17",
        24: "'The LORD is my shepherd; I shall not want.' - Psalm 23:1",
        25: "'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.' - Galatians 5:22",
        26: "'He is not here; he has risen, just as he said.' - Matthew 28:6",
        27: "'Give thanks to the LORD, for he is good; his love endures forever.' - Psalm 107:1",
        28: "'The LORD is my light and my salvation—whom shall I fear?' - Psalm 27:1",
        29: "'The righteous cry out, and the LORD hears them; he delivers them from all their troubles.' - Psalm 34:17",
        30: "'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.' - Philippians 4:6",
        31: "'But the Lord is faithful, and he will strengthen you and protect you from the evil one.' - 2 Thessalonians 3:3"
    },
    "August": {
        1: "'The LORD is near to the brokenhearted and saves the crushed in spirit.' - Psalm 34:18",
        2: "'And we know that in all things God works for the good of those who love him.' - Romans 8:28",
        3: "'For God did not give us a spirit of timidity, but a spirit of power, of love and of self-discipline.' - 2 Timothy 1:7",
        4: "'The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you.' - Numbers 6:24-25",
        5: "'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.' - Galatians 5:22",
        6: "'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.' - Nahum 1:7",
        7: "'Let all that you do be done in love.' - 1 Corinthians 16:14",
        8: "'Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.' - Joshua 1:9",
        9: "'In all your ways submit to him, and he will make your paths straight.' - Proverbs 3:6",
        10: "'Cast all your anxiety on him because he cares for you.' - 1 Peter 5:7",
        11: "'The LORD is my strength and my shield; my heart trusts in him, and he helps me.' - Psalm 28:7",
        12: "'The righteous cry out, and the LORD hears them; he delivers them from all their troubles.' - Psalm 34:17",
        13: "'Be still, and know that I am God.' - Psalm 46:10",
        14: "'He gives strength to the weary and increases the power of the weak.' - Isaiah 40:29",
        15: "'The name of the LORD is a fortified tower; the righteous run to it and are safe.' - Proverbs 18:10",
        16: "'I can do all this through him who gives me strength.' - Philippians 4:13",
        17: "'The LORD is my light and my salvation—whom shall I fear?' - Psalm 27:1",
        18: "'The LORD is compassionate and gracious, slow to anger, abounding in love.' - Psalm 103:8",
        19: "'And we know that in all things God works for the good of those who love him.' - Romans 8:28",
        20: "'The LORD will fight for you; you need only to be still.' - Exodus 14:14",
        21: "'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.' - Nahum 1:7",
        22: "'I sought the LORD, and he answered me; he delivered me from all my fears.' - Psalm 34:4",
        23: "'The LORD is my shepherd; I shall not want.' - Psalm 23:1",
        24: "'Let all that you do be done in love.' - 1 Corinthians 16:14",
        25: "'The righteous cry out, and the LORD hears them; he delivers them from all their troubles.' - Psalm 34:17",
        26: "'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.' - Nahum 1:7",
        27: "'The LORD is my light and my salvation—whom shall I fear?' - Psalm 27:1",
        28: "'Cast all your anxiety on him because he cares for you.' - 1 Peter 5:7",
        29: "'He gives strength to the weary and increases the power of the weak.' - Isaiah 40:29",
        30: "'The name of the LORD is a fortified tower; the righteous run to it and are safe.' - Proverbs 18:10",
        31: "'The LORD is my shepherd, I lack nothing.' - Psalm 23:1"
    },
}


